---
name: Test

on: pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run ESLint
        uses: DikaArdnt/actions/eslint@master
        with:
          args: dnsconfig.js

  dnscontrol:
    name: DNSControl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Preview
        uses: DikaArdnt/dnscontrol-action
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_API_USER: ${{ secrets.CLOUDFLARE_API_USER }}
        with:
          args: preview